<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />
  <Import Project="..\..\references\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>Blasphemy</AssemblyName>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Blasphemy</RootNamespace>
  </PropertyGroup>
</Project>