<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\references\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>DeepTorment</AssemblyName>
    <TargetFramework>net6.0</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>